### ISSUE TITLE
ResourceCache prewarm

### ISSUE THREAD

**Issue by dturn** [Shopify/krane#591]
The concurrency behavior of `DeployTask#check_initial_status` and `ResourceWatcher#sync_resources` is random. In the worst case all N threads could be servicing the same resource type. This would practically mean no parallelism since  n-1 threads would block on a mutex while the remaining thread is fetching the resources needed by that resource type. This behavior is especially painful for no-op deploys. 

A second related problem is that each resource type can fetch additional types in its sync loop. 

We can do better. We should add a `prewarm` function to the ResourceCache. A sketch of how this would look from @KnVerey :

```
cache = ResourceCache.new(@task_config)
cache.prewarm(resources)     
KubernetesDeploy::Concurrency.split_across_threads(resources) { |r| r.sync(cache) }
```

 The `prewarm` function would build a uniqe array from a new constant on resource:
`PREFETCH_KINDS_ON_SYNC = [Pod.kind, Deployment.kind, ReplicaSet.kind]`

```
def prewarm(resources)
   kinds = resources.flat_map { |r| r.PREFETCH_KINDS_ON_SYNC }.uniq
   KubernetesDeploy::Concurrency.split_across_threads(kinds) { |k| use_or_populate_cache(k) }
end
```

We're not intending `PREFETCH_KINDS_ON_SYNC` to be mandatory, if something is missed it can still be fetched in the `sync` function.  This is would simply be a performance improvement feature.

**Comment by RyanBrushett** [comment]
@dturn any thoughts/opinions on what resources absolutely should fetch as part of the cache warming?
Pods will certainly be a common one but does anything else stand out?

**Comment by KnVerey** [comment]
The prefetch should attempt to fetch everything that will be needed inline _for that particular sync_. Each class should tell you which kinds it will need, so that you can loop over the resources involved in the sync, de-dup the list of their classes, query each class for its list of required kinds, and then de-dup and fetch those (in parallel). To build the list for a class, you have to walk through its whole sync method. Note that this is going to break a fetch optimization we have on ReplicaSet (but it's probably worth it, performance-wise).
