### ISSUE TITLE
krane render and secrets.ejson

### ISSUE THREAD

**Issue by cjoudrey** [Shopify/krane#706]
Earlier today, in an effort to move away from `krane deploy`'s ERB rendering logic, we migrated part of our deploy tooling to use something similar to `krane render | krane deploy --stdin` as per the [upgrade guide](https://github.com/Shopify/krane/blob/ebd94c4ec2ffa6e790ae6d54d4c75fdc208e6c57/1.0-Upgrade.md).

Unfortunately, in doing so we inadvertently broke deployments that rely on `secrets.json` to create Kubernetes secrets. This was a blatant error on our side, but it lead to a good discussion with @dturn.

If we were to do this again, we'd have to do something along the lines of:

```
krane render -f path/to/templates > rendered_templates.yaml

deploy_paths = [rendered_templates.yaml]
deploy_paths << path/to/templates/secrets.ejson if exists?(path/to/templates/secrets.ejson)

krane deploy -f [deploy_paths].join
```

It made me wonder if `krane render` should have a way of expressing `secrets.ejson` such that we can blindly pipe it to `krane deploy` and it would just work.

I'm not sure if this is a terrible idea, but I was thinking we could have `krane render` pickup `secrets.ejson` and render it as a Kubernetes resource along the lines of:

```
apiVersion: krane.shopify.io/v1
kind: EjsonSecret
...
```

`krane deploy` would then be responsible for picking up those resources and transforming them into the Kubernetes secret that it creates today.

A different approach to this that has been discussed (in a different context) is to move away from `krane deploy`'s behaviour for this and having the Kubernetes secrets get created by a controller running on the destination cluster.

/cc @KnVerey @mkobetic as I've seen `krate` discussions regarding this

**Comment by dturn** [comment]
@timothysmith0609 any thoughts since you created the TemplateSet(s) classes

**Comment by KnVerey** [comment]
Internally, we're definitely going to be using an EjsonSecret resource that is converted to a Secret cluster-side: [internal issue](https://github.com/Shopify/krate/issues/85#issuecomment-588440886). This is really nice because it means krane doesn't need to read your ejson private key out of the cluster anymore. But the controller is (already) built in cloudbuddies, so it would be difficult to open-source. We could make krane generate that resource, but others would have to rebuild the controller for it. 

We could instead make it generate a virtual resource that is exactly the same as our real resource other than having a `krane.shopify.io` api group instead of `stable.shopify.io` so that `krane deploy` can know whether to process it (former) or leave it alone (latter). What concerns me about that plan is UX: (a) internally, that's a pretty subtle difference driving a behaviour change; (b) externally, would the deploy command still support creating Secrets directly from the ejson file, and if so why is two ways to do the same thing a good feature? Which way is going to be easier for most external users?

Another idea that may be bad: What if `krane render`, upon seeing an ejson file in the deploy directory, included the ejson as-is in the output stream, and `krane deploy` learned to recognize ejson by content in addition to by filename? My thought is that it is a bit strange that the render command effectively drops a resource today.

**Comment by dturn** [comment]
I think having `krane render` just emit the ejson as a document and then have `krane deploy` recognize it based on the public key field is worth a quick spike. I think its the least surprising option, assuming it doesn't make the code too complicated.

**Comment by timothysmith0609** [comment]
I agree with Danny, hopefully it won't be too painful to parse the ejson secrets out of the incoming set of templates (seems straightforward enough).

**Comment by KnVerey** [comment]
I just thought of a big downside of what I proposed / advantage of CJ's original suggestion: emitting ejson (even yaml-formatted) alongside k8s resources breaks interoperability. To give a concrete example, our k8s template validator currently essentially does `krane render` and then passes each document received to a series of validation tools. That needs to continue to work. I'm thinking either:

(1) We go with the virtual resource solution, which would also allow the secrets to be transformed and validated (other than the existence of the public key) by downstream tools if we publish the virtual resource schema. Downside is that we now accept encrypted secrets two different ways and have to maintain two different implementations (one of which will have to convert the virtual resource back to ejson to decrypt it).

(2) We make `render` capable of emitting ejson, but make it opt-in with a flag/arg. This is easer for us for sure, but then we haven't really solved the UX issue that `render` drops a resource, and users still can't construct a pipeline like `krane render | kubeval | krane deploy` without writting custom code in the middle.

**Comment by timothysmith0609** [comment]
I think having `krane` output kubernetes resources, and _only_ kubernetes resources, is advantageous for the reasons you describe. Perhaps another way to approach the problem is to make passing in secrets _more_ explicit via `krane deploy`. That is, necessitate supplying a flag (`--secrets=[SECRETS]`, e.g.) to `krane deploy` instead of combining them with the `--filenames` flag. 

The advantage here is that we preserve the semantics of what resources (provided by `--filenames`) _are_ (k8s yaml) between different krane commands and make an explicit guarantee that only such documents are to be considered valid. The downside is that this is a breaking change, which will require client-side updates.

Ultimately, I think trying to shoehorn EJSON secrets into the _resource_ pipeline is not the right way to think about this, unless we go all the way to representing them as a virtual resource. Absent that, I think secrets are more of a deploy concern than a rendering concern so let's make that explicit and stop conflating resources and secrets together.

**Comment by timothysmith0609** [comment]
After speaking with @KnVerey and @RyanBrushett , we are leaning towards representing EJSON as a virtual k8s resource. `krane render` will transform `secrets.ejson` into a kubernetes representation (e.g. with `kind`, `apiVersion`, `metadata`) and `krane deploy` will have a mechanism to translate that representation into the actual EJSON.

Provided we publish a schema for this representation, we can now safely do something like `krane render | kubeval | krane deploy -f -`. However, we need to address the following:

If `render` passes through a secret, and `krane deploy` is already including the secret file explicitly, ensure proper behaviour (e.g. dedup, ensure no errors, etc.).

>Downside is that we now accept encrypted secrets two different ways and have to maintain two different implementations (one of which will have to convert the virtual resource back to ejson to decrypt it).  

Hopefully we can contain this logic without having it bleed out into the rest of the code. the `TemplateSets` module seems like it should be able to deal with this without causing undue friction elsewhere.

@cjoudrey will this work for your needs?

**Comment by timothysmith0609** [comment]
We've decided to postpone any further work on this, as it's unclear at this moment if our proposed solution is going to be worthwhile in the long run. We can revisit this if the issue becomes more pressing in the future.
