### ISSUE TITLE
Add support for `OnDelete` update strategy when checking for a successful deploy

### ISSUE THREAD

**Issue by null-sleep** [Shopify/krane#912]
# Feature request

- [x] If the maintainers agree with the feature as described here, I intend to submit a Pull Request myself.<sup>1</sup>

**Proposal:**

For the `OnDelete` update strategy when checking for a successful deploy using [`deploy_succeeded?`, `krane` does not check if the rollout is successful and instead prints a warning message and moves on](https://github.com/Shopify/krane/blob/c9e81f7c824ae86310ab12aa422336ab0c9a314a/lib/krane/kubernetes_resource/stateful_set.rb#L21-L26
). The message given is: `# Gem cannot monitor update since it doesn't occur until delete`.
1. This presumes if the update strategy is `OnDelete`, there is nothing in place to roll the pods which is not always true. Ex. K8s operators used to rollout pods can use the `OnDelete` strategy to control the order of pod updates.
2. `deploy_succeeded?` in `krane` simply checks if all pods are on the updated revision and ready, the same logical check works for `OnDelete`, and so updates can still be monitored. (It's still useful to print a WARN saying OnDelete requires pod deletes.)

I propose that `krane` should support checking for a deploy being successful when the update strategy in `OnDelete` and prints a warning message to inform the user that pods have to be deleted to be updated. 

[A project at Shopify](https://github.com/Shopify/zonal-deploy-controller) would already benefit from this addition. This project is used to control how pods of a statefulsets are updated by updating all pods in a zone and uses the `OnDelete` strategy. By allowing to watch for successful deploys, this will allow `krane` and `shipit/buildkite` pipelines at Shopify to work seamlessly. Currently if we use `OnDelete`, shipit is unable to track the status of the deploy.

**Comment by KnVerey** [comment]
> We seem to have agreement on adding this behind a flag. The flag used when discussing was --watch-statefulsets but I think --watch-ondelete might be more accurate.

I suggest extending the [`krane.shopify.io/required-rollout` annotation](https://github.com/Shopify/krane#customizing-behaviour-with-annotations) to StatefulSet for this purpose, to allow the behaviour to be controlled on a per-resource basis using a style Krane users are already accustomed to. I suggest the only accepted values be `full` and `none`. The effective default value should be "full" for RollingUpdate SS. For OnDelete SS, I think it depends on whether or not the Krane team is willing to cut a major version for this, since defaulting to expecting progress where we used to expect nothing could be a breaking change. Arguably, defaulting to watching as much of the rollout as possible is the better default for a rollout monitoring tool, and having the default value not change based on part of the SS is easier to understand.

**Comment by ayana-s** [comment]
When putting our changes behind an annotation, we realized we'll need to add definitions for the `full` and `none` values of the `required-rollout` annotation, so that the annotation is compatible with StatefulSet. 

eg. Currently, a Deployment with the `none` annotation is marked as successful once the latest replicaSet has been created, but StatefulSets don't use replicaSets create/delete pods (unlike Deployments). 

The [definitions are currently as follows](https://github.com/Shopify/krane#customizing-behaviour-with-annotations): 
> `full`: The deployment is successful when all pods in the new `replicaSet` are ready.
> `none`: The deployment is successful as soon as the new `replicaSet` is created for the deployment.

Any recommended values to use for StatefulSets that represent a successful deploy with these annotations enabled? As a starting point, thoughts on the following?

- `full`: for StatefulSets, the deployment is successful when `observedGeneration == generation` AND all the replica values are equal [(example)](https://github.com/Shopify/krane/pull/926/files#diff-0e5baa0d520c6bf5a5bfcdfc79db4226ceae8e59445e4d2eb3b95969eb5a2990R36-R38)
- `none`: for StatefulSets, the deployment is successful when `observedGeneration == generation` [(example)](https://github.com/Shopify/krane/pull/926/files#diff-0e5baa0d520c6bf5a5bfcdfc79db4226ceae8e59445e4d2eb3b95969eb5a2990R25-R35)

**Comment by ayana-s** [comment]
In [this PR](https://github.com/Shopify/krane/pull/926/files), I've updated krane to support checking for successful StatefulSet deploys when `updateStrategy: OnDelete`. I've extended the [krane.shopify.io/required-rollout annotation](https://github.com/Shopify/krane#customizing-behaviour-with-annotations) to be compatible with StatefulSet resources.

Now, for all StatefulSets, krane checks the following to confirm a successful deploy:
```
observed_generation == current_generation
status_data['updateRevision'] == pod_data["metadata"]["labels"]["controller-revision-hash"]
```

For `updateStrategy: OnDelete` && `required-rollout: full`, krane also checks:
```
replicas == readyReplicas == updatedReplicas
```

For `updateStrategy: OnDelete` with no specified required-rollout value, no additional checks are conducted. The code runs as it did previously.

For `updateStrategy: RollingUpdate`, the additional checks remain the same as before: 
```
replicas == readyReplicas == currentReplicas && currentRevision == updateRevision
```
